export VAGRANT_HOME=/Volumes/Data/Vagrant

alias JB='~/IntelliJIDEALicenseServer_darwin_amd64 -p 40000 & disown'
alias apachestart='apachectl start'
alias apachestop='apachectl stop'
alias gcc='/usr/local/Cellar/gcc@5/5.4.0_1/bin/gcc-5'
alias git='/usr/local/Cellar/git/2.11.1/bin/git'
alias ls='ls -GFh'
alias portlist='sudo lsof -i -P | grep -i "listen"'
#alias python='/usr/local/bin/python2'
#alias PYTHONHOME='/usr/local/Cellar/python/2.7.13_1/bin'
alias ruby='/usr/local/bin/ruby'
alias sshnopa='ssh -o PubkeyAuthentication=no'
alias xdebugdis56='cat /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini | sed -e "s/xdebug.default_enable = 1/xdebug.default_enable = 0/" | sed -e "s/xdebug.remote_enable = 1/xdebug.remote_enable = 0/" > /tmp/ext-xdebug.ini.tmp; mv /tmp/ext-xdebug.ini.tmp /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini'
alias xdebugdis70='cat /usr/local/etc/php/7.0/conf.d/ext-xdebug.ini | sed -e "s/xdebug.default_enable = 1/xdebug.default_enable = 0/" | sed -e "s/xdebug.remote_enable = 1/xdebug.remote_enable = 0/" > /tmp/ext-xdebug.ini.tmp; mv /tmp/ext-xdebug.ini.tmp /usr/local/etc/php/7.0/conf.d/ext-xdebug.ini'
alias xdebugen56='cat /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini | sed -e "s/xdebug.default_enable = 0/xdebug.default_enable = 1/" | sed -e "s/xdebug.remote_enable = 0/xdebug.remote_enable = 1/" > /tmp/ext-xdebug.ini.tmp; mv /tmp/ext-xdebug.ini.tmp /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini'
alias xdebugen70='cat /usr/local/etc/php/7.0/conf.d/ext-xdebug.ini | sed -e "s/xdebug.default_enable = 0/xdebug.default_enable = 1/" | sed -e "s/xdebug.remote_enable = 0/xdebug.remote_enable = 1/" > /tmp/ext-xdebug.ini.tmp; mv /tmp/ext-xdebug.ini.tmp /usr/local/etc/php/7.0/conf.d/ext-xdebug.ini'
alias chromeremote='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222'
alias sshkeygen='ssh-keygen -t rsa -b 4096 -C'
alias freememory='python /usr/local/bin/checkmemory.py'
alias diskspace='df -h'
alias dirsize='du -sh'
alias filetree='find . -type f -print0 | xargs -0 du | sort -n | tail -10 | cut -f2 | xargs -I{} du -sh {}'
alias dirtree='du -sh * | sort -nr | head -n10'
alias ctags='/usr/local/bin/ctags'
alias addnodebin='export PATH="./node_modules/.bin:$PATH"'
